// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpQqbfNfd2HOTwjkQxwtVK9DE8Deo2LU0',
    appId: '1:366569072124:web:5bf9e9ff5dc2e964e6be79',
    messagingSenderId: '366569072124',
    projectId: 'login-fresh-demo',
    authDomain: 'login-fresh-demo.firebaseapp.com',
    storageBucket: 'login-fresh-demo.firebasestorage.app',
    measurementId: 'G-9CMFYBNWF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhg9gYc6IHBZjkj2NO5gvQfevWtMjDzcw',
    appId: '1:366569072124:android:24a39d5496fc7834e6be79',
    messagingSenderId: '366569072124',
    projectId: 'login-fresh-demo',
    storageBucket: 'login-fresh-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4efGuDQcm6jqGU6ThPN72rtARGgWopw',
    appId: '1:366569072124:ios:728b82d6ac88949de6be79',
    messagingSenderId: '366569072124',
    projectId: 'login-fresh-demo',
    storageBucket: 'login-fresh-demo.firebasestorage.app',
    iosBundleId: 'com.example.loginDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp4efGuDQcm6jqGU6ThPN72rtARGgWopw',
    appId: '1:366569072124:ios:728b82d6ac88949de6be79',
    messagingSenderId: '366569072124',
    projectId: 'login-fresh-demo',
    storageBucket: 'login-fresh-demo.firebasestorage.app',
    iosBundleId: 'com.example.loginDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpQqbfNfd2HOTwjkQxwtVK9DE8Deo2LU0',
    appId: '1:366569072124:web:1574dd0ba5a99519e6be79',
    messagingSenderId: '366569072124',
    projectId: 'login-fresh-demo',
    authDomain: 'login-fresh-demo.firebaseapp.com',
    storageBucket: 'login-fresh-demo.firebasestorage.app',
    measurementId: 'G-5Q14W1QF9P',
  );
}
